### ISSUE TITLE
Some Product ID's are not working...

### ISSUE THREAD

**Issue by developer2013** [1element/product-price-watch#2]
Hello, 

some product id's are not working in the script, do you have any idea why? it works for my but some are not working for the german amazon website. 

Thank You
Carsten

**Comment by 1element** [comment]
Hi Carsten,

do you have an example product id that does not work? Probably the price selector (.a-color-price) does not match, but if you provide an example configuration I can take a closer look at it.

Best regards

**Comment by developer2013** [comment]
Hello, 

now it's perfect working. thanks Carsten
